name: 🚀 Новая функция
description: Предложить улучшение или новый функционал
title: "[FEATURE] "
labels: ["enhancement", "priority: medium"]
assignees: []
body:
  - type: textarea
    id: why
    attributes:
      label: Зачем это нужно?
      description: Какую проблему пользователя или разработчика это решит?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Предлагаемое решение
      description: Как вы видите реализацию?
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Альтернативы
      description: Какие ещё варианты вы рассматривали?
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Дополнительная информация
      description: Ссылки, контекст, скриншоты.
    validations:
      required: false